import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { Reveal, ScrollFocusTitle } from "@/components/motion";
import { caseStudies } from "@/lib/content";

const testimonialPlaceholders = [
  { name: "Google for Developers", role: "DevFest Students Edition", tone: "peach", copy: "Supporting feedback from the team closest to the work.", image: "/Testimonials/Testimonials .jpg" },
  { name: "Community partner", role: "Organization pending", tone: "sage", copy: "This card is reserved for a partner who can speak to Adam's ability to bring people and organizations around a shared objective." },
  { name: "Program stakeholder", role: "Name and role pending", tone: "plum", copy: "A sourced testimonial about community activation, partnerships or on-the-ground delivery will replace this temporary copy." },
  { name: "Ecosystem collaborator", role: "Organization pending", tone: "blue", copy: "Final social proof will be published only after the name, role, wording and permission have been verified." },
];

export default function Home() {
  return <main className="reference-home">
    <section className="reference-hero section-shell">
      <p className="scroll-prompt"><span /> Keep Scrolling :)</p>
      <ScrollFocusTitle className="reference-title" lines={["ECOSYSTEM & COMMUNITY OPERATOR,", "PARTNERSHIPS BUILDER,", "PROGRAM STRATEGIST"]} />
      <div className="reference-intro"><div className="reference-copy"><p>I build the systems around communities, programs, events and partnerships that help organizations reach people, create meaningful participation and turn participation into opportunity.</p><p>My work sits at the intersection of community, partnerships, events and technology. I move between strategy and delivery—mapping ecosystems, coordinating stakeholders, troubleshooting constraints and getting the work into the real world.</p><p>How a person goes from discovering a community → finding a reason to participate → gaining useful access or skills → returning to contribute and lead, is the system I care about.</p><Link className="reference-link" href="/work">Explore selected work <ArrowUpRight /></Link></div><div className="reference-portrait"><Image src="/Personal pictures_/Close out .jpg" alt="Portrait of Adam Bello" fill priority sizes="(max-width: 760px) 100vw, 60vw" /></div></div>
    </section>
    <section className="reference-testimonials section-shell"><div className="reference-section-title"><h2>TESTIMONIALS</h2><p>What people I&apos;ve worked<br />with say about me</p></div><div className="testimonial-lead"><p>Credibility is strongest when it comes from the people closest to the work. This section is intentionally structured now and will only publish testimonials that are verified and approved.</p></div><div className="testimonial-stack">{testimonialPlaceholders.map((item, index) => <Reveal key={item.name} className={`reference-testimonial ${item.tone} card-${index + 1}`}><div className="testimonial-person"><span className="avatar-placeholder">AB</span><div><strong>{item.name}</strong><small>{item.role}</small></div><b>“</b></div><p>{item.copy}</p>{item.image && <div className="testimonial-proof"><Image src={item.image} alt="Google for Developers feedback for Adam Bello" fill sizes="(max-width: 760px) 90vw, 46vw" /></div>}</Reveal>)}</div></section>
    <section id="work" className="reference-highlights section-shell"><div className="highlight-image"><Image src="/Speaking session_/Physical Speaking session  (1).jpg" alt="Adam Bello speaking at an in-person session" fill sizes="(max-width: 760px) 100vw, 35vw" /></div><div className="highlight-copy"><h2>HIGHLIGHTS</h2><p>If this is your first time discovering my work, start with these community, partnership and program case studies.</p><div className="highlight-list">{caseStudies.slice(0, 6).map((study) => <Link key={study.slug} href={`/work/${study.slug}`}><span>CASE STUDY</span><strong>{study.title} — {study.eyebrow}</strong><i /></Link>)}</div></div></section>
    <section className="reference-programs section-shell"><div className="reference-section-title"><h2>PROGRAMS<br />&amp; EVENTS</h2><p>Strategy becomes real<br />in the field.</p></div><div className="programs-grid"><div className="programs-image"><Image src="/Build with AI_/IMG_7245.JPEG" alt="Participants working during a Build with AI program" fill sizes="(max-width: 760px) 100vw, 46vw" /></div><div className="programs-copy"><p>I work across technology events, developer programs, career initiatives, workshops and community gatherings—building the operating structure that helps the right people participate.</p><p>The goal is not an event that looks busy for one day. It is a useful experience with a clear path toward learning, building, access, partnerships or future contribution.</p></div><Link className="programs-cta" href="/work-with-me">Want to build a program<br />or activate a community?<span /><ArrowUpRight /></Link></div><div className="future-programs"><h3>Future programs<br />and engagements</h3><p>Planning a technology program, community activation, partnership or event? <Link href="/contact">Get in touch.</Link></p></div></section>
  </main>;
}
